// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VuePack
{
    static class Vsix
    {
        public const string Id = "4163aa08-9878-4b1c-a1ee-58ab67f7db5b";
        public const string Name = "Vue.js Pack";
        public const string Description = @"Contains HTML Intellisense and code snippets for the Vue.js JavaScript library";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vue.js, snippets, javascript";
    }
}
